DROP TABLE CATEGORIA CASCADE CONSTRAINTS;
DROP TABLE CLIENTES CASCADE CONSTRAINTS;
DROP TABLE DETALLE_DE_ORDEN CASCADE CONSTRAINTS;
DROP TABLE ORDEN_DE_VENTA CASCADE CONSTRAINTS;
DROP TABLE PAIS CASCADE CONSTRAINTS;
DROP TABLE PRODUCTOS CASCADE CONSTRAINTS;
DROP TABLE VENDEDORES CASCADE CONSTRAINTS;
